In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("Cars_data.xlsx")

In [3]:
df

,تاریخ,کیلومتر کارکرد,شماره شاسی,سازنده,Model,Type,قیمت بازار,قیمت کارخانه,توضیحات
0,1400-1-تیر,24393.0,NA0000000000000200,سایپا,پراید,Hatchback,17049382.0,17000000.0,بی رنگ
1,1400-2-تیر,18177.0,NA0000000000000201,سایپا,پراید,Hatchback,20059011.0,17000000.0,بیرنگ
2,1400-3-تیر,20600.0,NA0000000000000202,سایپا,پراید,Hatchback,17085239.0,17000000.0,زدگی
3,1400-4-تیر,26210.0,NA0000000000000203,سایپا,پراید,Hatchback,19220924.0,17000000.0,تصادف
4,1400-5-تیر,24213.0,NA0000000000000204,سایپا,پراید,Hatchback,20566626.0,17000000.0,بدون تصادف
...,...,...,...,...,...,...,...,...,...
192,1400-7-مرداد,20468.0,NA0000000000000392,ایرانخودرو,پژو206,Sedan,27423787.0,21000000.0,زدگی
193,1400-8-مرداد,20747.0,NA0000000000000393,ایرانخودرو,پژو206,Sedan,25184712.0,21000000.0,تصادف
194,1400-9-مرداد,20397.0,NA0000000000000394,ایرانخودرو,پژو206,Sedan,23437833.0,21000000.0,بدون تصادف
195,1400-10-مرداد,24358.0,NA0000000000000395,ایرانخودرو,پژو206,Sedan,29411805.0,21000000.0,فابریک
196,1400-11-مرداد,27363.0,NA0000000000000396,ایرانخودرو,پژو206,Sedan,25025798.0,21000000.0,بی رنگ

In [5]:
df_melted = pd.melt(df, value_vars = ['قیمت کارخانه' , 'قیمت بازار'])

In [6]:
df_melted

         variable       value
0    قیمت کارخانه  17000000.0
1    قیمت کارخانه  17000000.0
2    قیمت کارخانه  17000000.0
3    قیمت کارخانه  17000000.0
4    قیمت کارخانه  17000000.0
..            ...         ...
389    قیمت بازار  27423787.0
390    قیمت بازار  25184712.0
391    قیمت بازار  23437833.0
392    قیمت بازار  29411805.0
393    قیمت بازار  25025798.0

[394 rows x 2 columns]

In [29]:
table_data = df_melted.pivot_table(columns= 'variable' , values= 'value', aggfunc='sum')

In [30]:
table_data

variable    قیمت بازار  قیمت کارخانه
value     4.566667e+09  3.770000e+09

In [32]:
import os

In [35]:
os.listdir('./Data')

['Cars_data.xlsx', 'mordad.xlsx', 'shhrivar.xlsx', 'tir.xlsx']

In [37]:
df1 = pd.read_excel('./Data/mordad.xlsx')
df2 = pd.read_excel('./Data/shhrivar.xlsx')
df3 = pd.read_excel('./Data/tir.xlsx')

In [38]:
df1

,تاریخ,dfdgh,month,کیلومتر کارکرد,شماره شاسی,سازنده,Model,Type,قیمت بازار,قیمت کارخانه,توضیحات
0,1400,11,مرداد,27363,NA0000000000000396,ایرانخودرو,پژو206,Sedan,25025798.0,21000000.0,بی رنگ
1,1400,10,مرداد,24358,NA0000000000000395,ایرانخودرو,پژو206,Sedan,29411805.0,21000000.0,فابریک
2,1400,9,مرداد,20397,NA0000000000000394,ایرانخودرو,پژو206,Sedan,23437833.0,21000000.0,بدون تصادف
3,1400,8,مرداد,20747,NA0000000000000393,ایرانخودرو,پژو206,Sedan,25184712.0,21000000.0,تصادف
4,1400,7,مرداد,20468,NA0000000000000392,ایرانخودرو,پژو206,Sedan,27423787.0,21000000.0,زدگی
...,...,...,...,...,...,...,...,...,...,...,...
65,1400,5,مرداد,19889,NA0000000000000328,ایرانخودرو,پژو206,Sedan,26220352.0,21000000.0,تصادف
66,1400,4,مرداد,19206,NA0000000000000327,ایرانخودرو,پژو206,Sedan,26684438.0,21000000.0,زدگی
67,1400,3,مرداد,18483,NA0000000000000326,ایرانخودرو,پژو206,Sedan,27808602.0,21000000.0,بیرنگ
68,1400,2,مرداد,17491,NA0000000000000325,ایرانخودرو,پژو206,Sedan,26908142.0,21000000.0,بی رنگ
69,1400,1,مرداد,28874,NA0000000000000324,ایرانخودرو,پژو206,Sedan,25062713.0,21000000.0,بی رنگ

In [45]:
season_data = pd.concat([df1,df2,df3])

In [46]:
season_data

,تاریخ,dfdgh,month,کیلومتر کارکرد,شماره شاسی,سازنده,Model,Type,قیمت بازار,قیمت کارخانه,توضیحات
0,1400,11,مرداد,27363.0,NA0000000000000396,ایرانخودرو,پژو206,Sedan,25025798.0,21000000.0,بی رنگ
1,1400,10,مرداد,24358.0,NA0000000000000395,ایرانخودرو,پژو206,Sedan,29411805.0,21000000.0,فابریک
2,1400,9,مرداد,20397.0,NA0000000000000394,ایرانخودرو,پژو206,Sedan,23437833.0,21000000.0,بدون تصادف
3,1400,8,مرداد,20747.0,NA0000000000000393,ایرانخودرو,پژو206,Sedan,25184712.0,21000000.0,تصادف
4,1400,7,مرداد,20468.0,NA0000000000000392,ایرانخودرو,پژو206,Sedan,27423787.0,21000000.0,زدگی
...,...,...,...,...,...,...,...,...,...,...,...
57,1400,5,تیر,9646.0,NA0000000000000297,ایرانخودرو,پژو206,Hatchback,24895086.0,20000000.0,بدون رنگ
58,1400,4,تیر,27646.0,NA0000000000000296,ایرانخودرو,پژو206,Hatchback,28990287.0,20000000.0,بیرنگ
59,1400,3,تیر,26156.0,NA0000000000000295,ایرانخودرو,پژو206,Hatchback,26658029.0,20000000.0,پوسیدگی
60,1400,2,تیر,24707.0,NA0000000000000294,ایرانخودرو,پژو206,Hatchback,27429278.0,20000000.0,تصادف جزیی
61,1400,1,تیر,21593.0,NA0000000000000293,ایرانخودرو,پژو206,Hatchback,26096153.0,20000000.0,تصادف